<?php
/*
* This file is part of the Datapool CMS package.
* @package Datapool
* @author Carsten Wallenhauer <admin@datapool.info>
* @copyright 2023 to today Carsten Wallenhauer
* @license https://www.gnu.org/licenses/agpl-3.0.html AGPL-v3
*/
declare(strict_types=1);

namespace SourcePot\OPS;

interface OpsInterface{
    const CODES=['pBRE001'=>['msg'=>'Check digit not correct','type'=>'error'],
                'pBRE002'=>['msg'=>'No country code provided','type'=>'warning'],
                'pBRE003'=>['msg'=>'Kind code not found','type'=>'warning'],
                'pBRE004'=>['msg'=>'Date out of range','type'=>'warning'],
                'pBRE005'=>['msg'=>'No number format detected for this kind code','type'=>'warning'],
                'pBRE006'=>['msg'=>'Number transformation rule not specified','type'=>'warning'],
                'pBRE007'=>['msg'=>'Number outside number range','type'=>'warning'],
                'pBRE008'=>['msg'=>'Converted to Gregorian year','type'=>'warning'],
                'pBRE009'=>['msg'=>'Converted to Emperor year','type'=>'warning'],
                'pBRE010'=>['msg'=>'Date generated through lookup with input number','type'=>'warning'],
                'pBRE011'=>['msg'=>'No match found. Country code changed.','type'=>'warning'],
                'pBRE012'=>['msg'=>'Kind code in number does not match kind code supplied.','type'=>'error'],
                'pBRE013'=>['msg'=>'Output kind code different from extracted kind code.','type'=>'warning'],
                'pBRE014'=>['msg'=>'Kind code generated.','type'=>'warning'],
                'pBRE015'=>['msg'=>'Kind code transformed.','type'=>'warning'],
                'pBRE016'=>['msg'=>'Provided date is different from extracted date.','type'=>'warning'],
                'pBRE017'=>['msg'=>'Publication date set from extracted date.','type'=>'warning'],
                'pBRE018'=>['msg'=>'Application date set from extracted date.','type'=>'warning'],
                'pBRE019'=>['msg'=>'No kind code provided, setting it to A.','type'=>'warning'],
                'pBRE020'=>['msg'=>'Kind code does not start with a letter, setting it to A.','type'=>'warning'],
                'pBRE021'=>['msg'=>'Second character of provided kind code is not a digit, removing it.','type'=>'warning'],
                'pBRE022'=>['msg'=>'Date is before year 1617','type'=>'error'],
                'pBRE023'=>['msg'=>'Date is after current year + 2','type'=>'error'],
                'pBRE024'=>['msg'=>'Month is not between 1 and 12, month and day set to 0','type'=>'error'],
                'pBRE025'=>['msg'=>'Day is invalid, set to 0','type'=>'error'],
                'pBRE026'=>['msg'=>'Date is in the future.','type'=>'warning'],
                'pBRE027'=>['msg'=>'Date lookup with input number did not find anything.','type'=>'error'],
                'pBRE028'=>['msg'=>'Date generated through lookup with output number','type'=>'warning'],
                'pBRE029'=>['msg'=>'Date lookup with output number did not find anything.','type'=>'error'],
                'pBRE030'=>['msg'=>'Document with kind code found in master Document with kind code found in master database.database.','type'=>'warning'],
                'pBRE031'=>['msg'=>'Kind code updated via lookup.Kind code updated via lookup.','type'=>'warning'], 
                'pBRE032'=>['msg'=>'Kind code lookup did not find anything.code lookup did not find anything.','type'=>'warning'],
                'pBRE033'=>['msg'=>'REFI kind code lookup did not find anything.','type'=>'warning'],
                'pBRE034'=>['msg'=>'REFI not allowed.','type'=>'warning'],
                'pBRE035'=>['msg'=>'Citing target set.','type'=>'warning'],
                'pBRE036'=>['msg'=>'Citing target not set, kind codes do not match.match.','type'=>'warning'],
                'pBRE037'=>['msg'=>'Date corrected via kind code lookup.','type'=>'warning'],
                'pBRE038'=>['msg'=>'Date set via kind code lookup.','type'=>'warning'],
                'pBRE039'=>['msg'=>'No Active Priority','type'=>'warning'],
                'pBRE040'=>['msg'=>'Error in refi kind code lookup.','type'=>'error'],
                'pBRE041'=>['msg'=>'Last change origin of targetId was human, setting targetId as rawId.','type'=>'warning'],
                'pBRE042'=>['msg'=>'The provided document is a valid DOCDB format.','type'=>'warning'],
                'pBRE043'=>['msg'=>'The provided document is not a valid DOCDB format.','type'=>'error'],
                'pBRE044'=>['msg'=>'Rules without country used for transforming Rules without country used for transforming the number.','type'=>'warning'],
                'pBRE045'=>['msg'=>'Provided country code is different than Provided country code is different than extracted country code.','type'=>'warning'],
                'pBRE046'=>['msg'=>'Kind code rule did not allow configured rules Kind code rule did not allow configured rules to transform number.','type'=>'error'],
                'pBRE047'=>['msg'=>'Meaningless digits removed from number','type'=>'warning'],
                'pBRE048'=>['msg'=>'Date generated through sequence number lookup','type'=>'warning'],
                'pBRE049'=>['msg'=>'Date lookup with sequence did not find anything','type'=>'warning'],
                'pBRE050'=>['msg'=>'RID found in master database','type'=>'warning'],
                'pBRE051'=>['msg'=>'RID not found in master database','type'=>'warning'],
                'pBRE052'=>['msg'=>'Document found by RID in master database','type'=>'warning'],
                'pBRE053'=>['msg'=>'Document not found by RID in master database','type'=>'warning'],
                'pBRE054'=>['msg'=>'Error in RID lookup','type'=>'warning'],
                'pBRE055'=>['msg'=>'Document found in master database','type'=>'warning'],
                'pBRE056'=>['msg'=>'Document not found in master database','type'=>'warning'],
                'pBRE057'=>['msg'=>'preBRE not configured for validation','type'=>'warning'],
                'pBRE058'=>['msg'=>'Kind code is missing for validation','type'=>'warning'],
                'pBRE059'=>['msg'=>'Date is missing for validation','type'=>'warning'],
                'pBRE060'=>['msg'=>'Country code is missing for validation','type'=>'error'],
                'pBRE061'=>['msg'=>'Country code is invalid for validation','type'=>'error'],
                'pBRE100'=>['msg'=>'Duplicate priority removed','type'=>'warning'],
                'pBRE101'=>['msg'=>'Country code standardised','type'=>'warning'],
                'pBRE102'=>['msg'=>'Leading/trailing characters removed','type'=>'warning'],
                'pBRE103'=>['msg'=>'Country code removed for valid PCT number format','type'=>'warning'],
                'pBRE104'=>['msg'=>'Chinese check digit removed','type'=>'warning'],
                'pBRE105'=>['msg'=>'Country code derived from serial number','type'=>'warning'],
                'pBRE106'=>['msg'=>'Country code EP/EU changed to EM','type'=>'warning'],
                'pBRE107'=>['msg'=>'Duplicate country code removed','type'=>'warning'],
                'pBRE108'=>['msg'=>'Country code changed due to date','type'=>'warning'],
                'pBRE109'=>['msg'=>'Country code derived from serial number','type'=>'warning'],
                'pBRE110'=>['msg'=>'Kind code set to W for PCT protection type','type'=>'warning'],
                'pBRE111'=>['msg'=>'Kind code set to W for Epoque PCT priority','type'=>'warning'],
                'pBRE112'=>['msg'=>'EP A priority created from self claimer','type'=>'warning'],
                'pBRE113'=>['msg'=>'Kind code set to W for protection type PCT','type'=>'warning'],
                'pBRE114'=>['msg'=>'LMI set for PCT priority','type'=>'warning'],
                'pBRE115'=>['msg'=>'Country code set to WO for Epoque format','type'=>'warning'],
                'pBRE116'=>['msg'=>'Country code removed for external PCT format','type'=>'warning'],
                'pBRE117'=>['msg'=>'EP priority generated for HU translation','type'=>'warning'],
                'pBRE118'=>['msg'=>'LMI Removed','type'=>'warning'],
                'pBRE119'=>['msg'=>'Kind code W forced to use the no country rules','type'=>'warning'],
                'pBRE120'=>['msg'=>'Kind code set to W for application associated with publication country WO','type'=>'warning'],
                'pBRE121'=>['msg'=>'Country code for priority starting with DM changed to XH','type'=>'warning'],
                'pBRE122'=>['msg'=>'new country code set for KR citation','type'=>'warning'],
                'pBRE123'=>['msg'=>'Kind code derived from serial number','type'=>'warning'],
                'pBRE124'=>['msg'=>'Italian priority selected from multiple IT priorities provided','type'=>'warning'],
                'pBRE126'=>['msg'=>'Kind code derived from number','type'=>'warning'],
                'pBRE127'=>['msg'=>'Kind code removed from nu mber','type'=>'warning'],
                'pBRE128'=>['msg'=>'JP single emperor year prepended with 0','type'=>'warning'],
                'pBRE129'=>['msg'=>'Application kind code set to U for utility model publication','type'=>'warning'],
                'pBRE130'=>['msg'=>'Application kind code set to T for national translation of EP','type'=>'warning'],
                'pBRE131'=>['msg'=>'Spaces before/after separator removed','type'=>'warning'],
                'pBRE132'=>['msg'=>'Leading zero added for single digit years (2000 2009)','type'=>'warning'],
                'pBRE133'=>['msg'=>'Substition of Chinese comma by a regular comma','type'=>'warning'],
                'pBRE134'=>['msg'=>'New kind code U set for KR citation','type'=>'warning'],
                'pBRE135'=>['msg'=>'New raw ID set for KR citation','type'=>'warning'],
                'pBRE136'=>['msg'=>'New kind code set for KR citation','type'=>'warning'],
                'pBRE137'=>['msg'=>'Transformed small caps characters to uppercase','type'=>'warning'],
                'pBRE138'=>['msg'=>'Country code set to IB for DOCDB format','type'=>'warning'],
                'pBRE139'=>['msg'=>'Priority removed','type'=>'warning'],
                'pBRE999'=>['msg'=>'Number could not be transformed, setting number from original','type'=>'error'],
                'BRE000'=>['msg'=>'Unknown error code','type'=>'error'],
                'BRE001'=>['msg'=>'Number Standardization Stopped','type'=>'error'],
                'BRE002'=>['msg'=>'Number Standardization Stopped Routed to Post Processing','type'=>'error'],
                'BRE003'=>['msg'=>'RawId not Defined','type'=>'error'],
                'BRE004'=>['msg'=>'Country Code not Valid','type'=>'error'],
                'BRE005'=>['msg'=>'Exception in date lookup','type'=>'error'],
                'BRE006'=>['msg'=>'No Matching Pattern Found','type'=>'error'],
                'BRE007'=>['msg'=>'Failed to convert sequence number for document','type'=>'error'],
                'BRE008'=>['msg'=>'Illegal Country Code WO for APP PRI','type'=>'error'],
                'BRE009'=>['msg'=>'Invalid Sequence Number in KindCodeSet','type'=>'error'],
                'BRE010'=>['msg'=>'Invalid Sequence Number in GenerateTargetId','type'=>'error'],
                'BRE011'=>['msg'=>'Invalid Length for ','type'=>'error'],
                'BRE012'=>['msg'=>'SN Length Over Max Size','type'=>'error'],
                'BRE013'=>['msg'=>'Kind Code not valid for this Time Period','type'=>'error'],
                'BRE014'=>['msg'=>'Attempt to Apply Pattern that was not Parsed','type'=>'error'],
                'BRE015'=>['msg'=>'Failed to Convert Year Group','type'=>'error'],
                'BRE016'=>['msg'=>'Failed to Convert Sequence Number Group','type'=>'error'],
                'BRW001'=>['msg'=>'Country Code not Defined','type'=>'warning'],
                'BRW002'=>['msg'=>'Document Date not Defined','type'=>'warning'],
                'BRW003'=>['msg'=>'Kind Code not Defined','type'=>'warning'],
                'BRW004'=>['msg'=>'Illegal Country Code for APP PRI','type'=>'warning'],
                'BRW005'=>['msg'=>'DM found in raw id, using XH country','type'=>'warning'],
                'BRW006'=>['msg'=>'Using Default Country Pattern','type'=>'warning'],
                'BRW007'=>['msg'=>'Country Code Replaced','type'=>'warning'],
                'BRW008'=>['msg'=>'Year indication from date field','type'=>'warning'],
                'BRW009'=>['msg'=>'Sequence number adjusted to','type'=>'warning'],
                'BRW010'=>['msg'=>'Kind Code Relation not Allowed','type'=>'warning'],
                'BRW011'=>['msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'],
                'BRW012'=>['msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'],
                'BRW013'=>['msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'],
                'BRW014'=>['msg'=>'No Kind Code or Generation Format Defined','type'=>'warning'],
                'BRW015'=>['msg'=>'No Date Found. Trigger lookup','type'=>'warning'],
                'BRW016'=>['msg'=>'Date Lookup Did not Find Anything','type'=>'warning'],
                'BRW017'=>['msg'=>'Year Replacement Failed. No Date Defined in the Input','type'=>'warning'],
                'BRW018'=>['msg'=>'Year Defined in Target Format, but no Date Defined','type'=>'warning'],
                'BRW019'=>['msg'=>'Document Found in DB','type'=>'warning'],
                'BRW020'=>['msg'=>'Kind code replaced by preferred lookup value','type'=>'warning'],
                'BRW021'=>['msg'=>'Kind code replaced but not with first preferred lookup value','type'=>'warning'],
                'BRW022'=>['msg'=>'Lookup found values which are not in preferred list','type'=>'warning'],
                'BRW023'=>['msg'=>'Kind code lookup did not find anything','type'=>'warning'],
                'BRW024'=>['msg'=>'Lookup for kind codes with date contains more than one value','type'=>'warning'],
                'BRW026'=>['msg'=>'Lookup found documents which are not in preferred list','type'=>'warning'],
                'BRW027'=>['msg'=>'Invalid date format','type'=>'warning'],
                'BRW028'=>['msg'=>'Invalid date format','type'=>'warning'],
                'BRW030'=>['msg'=>'Kind code lookup without date found values','type'=>'warning'],
                'BRW031'=>['msg'=>'No Kindcode format defined, kindcode first char matches a valid kindcode','type'=>'warning'],
                'BRW032'=>['msg'=>'No Kindcode format defined, kindcode matches a valid kindcode','type'=>'warning'],
                ];
}
?>
