<?php
/*
* This file is part of the Datapool CMS package.
* @package Datapool
* @author Carsten Wallenhauer <admin@datapool.info>
* @copyright 2023 to today Carsten Wallenhauer
* @license https://www.gnu.org/licenses/agpl-3.0.html AGPL-v3
*/
declare(strict_types=1);

namespace SourcePot\OPS;

interface OpsInterface{
    const CODES=array('pBRE001'=>array('msg'=>'Check digit not correct','type'=>'error'),
                       'pBRE002'=>array('msg'=>'No country code provided','type'=>'warning'),
                       'pBRE003'=>array('msg'=>'Kind code not found','type'=>'warning'),
                       'pBRE004'=>array('msg'=>'Date out of range','type'=>'warning'),
                       'pBRE005'=>array('msg'=>'No number format detected for this kind code','type'=>'warning'),
                       'pBRE006'=>array('msg'=>'Number transformation rule not specified','type'=>'warning'),
                       'pBRE007'=>array('msg'=>'Number outside number range','type'=>'warning'),
                       'pBRE008'=>array('msg'=>'Converted to Gregorian year','type'=>'warning'),
                       'pBRE009'=>array('msg'=>'Converted to Emperor year','type'=>'warning'),
                       'pBRE010'=>array('msg'=>'Date generated through lookup with input number','type'=>'warning'),
                       'pBRE011'=>array('msg'=>'No match found. Country code changed.','type'=>'warning'),
                       'pBRE012'=>array('msg'=>'Kind code in number does not match kind code supplied.','type'=>'error'),
                       'pBRE013'=>array('msg'=>'Output kind code different from extracted kind code.','type'=>'warning'),
                       'pBRE014'=>array('msg'=>'Kind code generated.','type'=>'warning'),
                       'pBRE015'=>array('msg'=>'Kind code transformed.','type'=>'warning'),
                       'pBRE016'=>array('msg'=>'Provided date is different from extracted date.','type'=>'warning'),
                       'pBRE017'=>array('msg'=>'Publication date set from extracted date.','type'=>'warning'),
                       'pBRE018'=>array('msg'=>'Application date set from extracted date.','type'=>'warning'),
                       'pBRE019'=>array('msg'=>'No kind code provided, setting it to A.','type'=>'warning'),
                       'pBRE020'=>array('msg'=>'Kind code does not start with a letter, setting it to A.','type'=>'warning'),
                       'pBRE021'=>array('msg'=>'Second character of provided kind code is not a digit, removing it.','type'=>'warning'),
                       'pBRE022'=>array('msg'=>'Date is before year 1617','type'=>'error'),
                       'pBRE023'=>array('msg'=>'Date is after current year + 2','type'=>'error'),
                       'pBRE024'=>array('msg'=>'Month is not between 1 and 12, month and day set to 0','type'=>'error'),
                       'pBRE025'=>array('msg'=>'Day is invalid, set to 0','type'=>'error'),
                       'pBRE026'=>array('msg'=>'Date is in the future.','type'=>'warning'),
                       'pBRE027'=>array('msg'=>'Date lookup with input number did not find anything.','type'=>'error'),
                       'pBRE028'=>array('msg'=>'Date generated through lookup with output number','type'=>'warning'),
                       'pBRE029'=>array('msg'=>'Date lookup with output number did not find anything.','type'=>'error'),
                       'pBRE030'=>array('msg'=>'Document with kind code found in master Document with kind code found in master database.database.','type'=>'warning'),
                       'pBRE031'=>array('msg'=>'Kind code updated via lookup.Kind code updated via lookup.','type'=>'warning'), 
                       'pBRE032'=>array('msg'=>'Kind code lookup did not find anything.code lookup did not find anything.','type'=>'warning'),
                       'pBRE033'=>array('msg'=>'REFI kind code lookup did not find anything.','type'=>'warning'),
                       'pBRE034'=>array('msg'=>'REFI not allowed.','type'=>'warning'),
                       'pBRE035'=>array('msg'=>'Citing target set.','type'=>'warning'),
                       'pBRE036'=>array('msg'=>'Citing target not set, kind codes do not match.match.','type'=>'warning'),
                       'pBRE037'=>array('msg'=>'Date corrected via kind code lookup.','type'=>'warning'),
                       'pBRE038'=>array('msg'=>'Date set via kind code lookup.','type'=>'warning'),
                       'pBRE039'=>array('msg'=>'No Active Priority','type'=>'warning'),
                       'pBRE040'=>array('msg'=>'Error in refi kind code lookup.','type'=>'error'),
                       'pBRE041'=>array('msg'=>'Last change origin of targetId was human, setting targetId as rawId.','type'=>'warning'),
                       'pBRE042'=>array('msg'=>'The provided document is a valid DOCDB format.','type'=>'warning'),
                       'pBRE043'=>array('msg'=>'The provided document is not a valid DOCDB format.','type'=>'error'),
                       'pBRE044'=>array('msg'=>'Rules without country used for transforming Rules without country used for transforming the number.','type'=>'warning'),
                       'pBRE045'=>array('msg'=>'Provided country code is different than Provided country code is different than extracted country code.','type'=>'warning'),
                       'pBRE046'=>array('msg'=>'Kind code rule did not allow configured rules Kind code rule did not allow configured rules to transform number.','type'=>'error'),
                       'pBRE047'=>array('msg'=>'Meaningless digits removed from number','type'=>'warning'),
                       'pBRE048'=>array('msg'=>'Date generated through sequence number lookup','type'=>'warning'),
                       'pBRE049'=>array('msg'=>'Date lookup with sequence did not find anything','type'=>'warning'),
                       'pBRE050'=>array('msg'=>'RID found in master database','type'=>'warning'),
                       'pBRE051'=>array('msg'=>'RID not found in master database','type'=>'warning'),
                       'pBRE052'=>array('msg'=>'Document found by RID in master database','type'=>'warning'),
                       'pBRE053'=>array('msg'=>'Document not found by RID in master database','type'=>'warning'),
                       'pBRE054'=>array('msg'=>'Error in RID lookup','type'=>'warning'),
                       'pBRE055'=>array('msg'=>'Document found in master database','type'=>'warning'),
                       'pBRE056'=>array('msg'=>'Document not found in master database','type'=>'warning'),
                       'pBRE057'=>array('msg'=>'preBRE not configured for validation','type'=>'warning'),
                       'pBRE058'=>array('msg'=>'Kind code is missing for validation','type'=>'warning'),
                       'pBRE059'=>array('msg'=>'Date is missing for validation','type'=>'warning'),
                       'pBRE060'=>array('msg'=>'Country code is missing for validation','type'=>'error'),
                       'pBRE061'=>array('msg'=>'Country code is invalid for validation','type'=>'error'),
                       'pBRE100'=>array('msg'=>'Duplicate priority removed','type'=>'warning'),
                       'pBRE101'=>array('msg'=>'Country code standardised','type'=>'warning'),
                       'pBRE102'=>array('msg'=>'Leading/trailing characters removed','type'=>'warning'),
                       'pBRE103'=>array('msg'=>'Country code removed for valid PCT number format','type'=>'warning'),
                       'pBRE104'=>array('msg'=>'Chinese check digit removed','type'=>'warning'),
                       'pBRE105'=>array('msg'=>'Country code derived from serial number','type'=>'warning'),
                       'pBRE106'=>array('msg'=>'Country code EP/EU changed to EM','type'=>'warning'),
                       'pBRE107'=>array('msg'=>'Duplicate country code removed','type'=>'warning'),
                       'pBRE108'=>array('msg'=>'Country code changed due to date','type'=>'warning'),
                       'pBRE109'=>array('msg'=>'Country code derived from serial number','type'=>'warning'),
                       'pBRE110'=>array('msg'=>'Kind code set to W for PCT protection type','type'=>'warning'),
                       'pBRE111'=>array('msg'=>'Kind code set to W for Epoque PCT priority','type'=>'warning'),
                       'pBRE112'=>array('msg'=>'EP A priority created from self claimer','type'=>'warning'),
                       'pBRE113'=>array('msg'=>'Kind code set to W for protection type PCT','type'=>'warning'),
                       'pBRE114'=>array('msg'=>'LMI set for PCT priority','type'=>'warning'),
                       'pBRE115'=>array('msg'=>'Country code set to WO for Epoque format','type'=>'warning'),
                       'pBRE116'=>array('msg'=>'Country code removed for external PCT format','type'=>'warning'),
                       'pBRE117'=>array('msg'=>'EP priority generated for HU translation','type'=>'warning'),
                       'pBRE118'=>array('msg'=>'LMI Removed','type'=>'warning'),
                       'pBRE119'=>array('msg'=>'Kind code W forced to use the no country rules','type'=>'warning'),
                       'pBRE120'=>array('msg'=>'Kind code set to W for application associated with publication country WO','type'=>'warning'),
                       'pBRE121'=>array('msg'=>'Country code for priority starting with DM changed to XH','type'=>'warning'),
                       'pBRE122'=>array('msg'=>'new country code set for KR citation','type'=>'warning'),
                       'pBRE123'=>array('msg'=>'Kind code derived from serial number','type'=>'warning'),
                       'pBRE124'=>array('msg'=>'Italian priority selected from multiple IT priorities provided','type'=>'warning'),
                       'pBRE126'=>array('msg'=>'Kind code derived from number','type'=>'warning'),
                       'pBRE127'=>array('msg'=>'Kind code removed from nu mber','type'=>'warning'),
                       'pBRE128'=>array('msg'=>'JP single emperor year prepended with 0','type'=>'warning'),
                       'pBRE129'=>array('msg'=>'Application kind code set to U for utility model publication','type'=>'warning'),
                       'pBRE130'=>array('msg'=>'Application kind code set to T for national translation of EP','type'=>'warning'),
                       'pBRE131'=>array('msg'=>'Spaces before/after separator removed','type'=>'warning'),
                       'pBRE132'=>array('msg'=>'Leading zero added for single digit years (2000 2009)','type'=>'warning'),
                       'pBRE133'=>array('msg'=>'Substition of Chinese comma by a regular comma','type'=>'warning'),
                       'pBRE134'=>array('msg'=>'New kind code U set for KR citation','type'=>'warning'),
                       'pBRE135'=>array('msg'=>'New raw ID set for KR citation','type'=>'warning'),
                       'pBRE136'=>array('msg'=>'New kind code set for KR citation','type'=>'warning'),
                       'pBRE137'=>array('msg'=>'Transformed small caps characters to uppercase','type'=>'warning'),
                       'pBRE138'=>array('msg'=>'Country code set to IB for DOCDB format','type'=>'warning'),
                       'pBRE139'=>array('msg'=>'Priority removed','type'=>'warning'),
                       'pBRE999'=>array('msg'=>'Number could not be transformed, setting number from original','type'=>'error'),
                       'BRE000'=>array('msg'=>'Unknown error code','type'=>'error'),
                       'BRE001'=>array('msg'=>'Number Standardization Stopped','type'=>'error'),
                       'BRE002'=>array('msg'=>'Number Standardization Stopped Routed to Post Processing','type'=>'error'),
                       'BRE003'=>array('msg'=>'RawId not Defined','type'=>'error'),
                       'BRE004'=>array('msg'=>'Country Code not Valid','type'=>'error'),
                       'BRE005'=>array('msg'=>'Exception in date lookup','type'=>'error'),
                       'BRE006'=>array('msg'=>'No Matching Pattern Found','type'=>'error'),
                       'BRE007'=>array('msg'=>'Failed to convert sequence number for document','type'=>'error'),
                       'BRE008'=>array('msg'=>'Illegal Country Code WO for APP PRI','type'=>'error'),
                       'BRE009'=>array('msg'=>'Invalid Sequence Number in KindCodeSet','type'=>'error'),
                       'BRE010'=>array('msg'=>'Invalid Sequence Number in GenerateTargetId','type'=>'error'),
                       'BRE011'=>array('msg'=>'Invalid Length for ','type'=>'error'),
                       'BRE012'=>array('msg'=>'SN Length Over Max Size','type'=>'error'),
                       'BRE013'=>array('msg'=>'Kind Code not valid for this Time Period','type'=>'error'),
                       'BRE014'=>array('msg'=>'Attempt to Apply Pattern that was not Parsed','type'=>'error'),
                       'BRE015'=>array('msg'=>'Failed to Convert Year Group','type'=>'error'),
                       'BRE016'=>array('msg'=>'Failed to Convert Sequence Number Group','type'=>'error'),
                       'BRW001'=>array('msg'=>'Country Code not Defined','type'=>'warning'),
                       'BRW002'=>array('msg'=>'Document Date not Defined','type'=>'warning'),
                       'BRW003'=>array('msg'=>'Kind Code not Defined','type'=>'warning'),
                       'BRW004'=>array('msg'=>'Illegal Country Code for APP PRI','type'=>'warning'),
                       'BRW005'=>array('msg'=>'DM found in raw id, using XH country','type'=>'warning'),
                       'BRW006'=>array('msg'=>'Using Default Country Pattern','type'=>'warning'),
                       'BRW007'=>array('msg'=>'Country Code Replaced','type'=>'warning'),
                       'BRW008'=>array('msg'=>'Year indication from date field','type'=>'warning'),
                       'BRW009'=>array('msg'=>'Sequence number adjusted to','type'=>'warning'),
                       'BRW010'=>array('msg'=>'Kind Code Relation not Allowed','type'=>'warning'),
                       'BRW011'=>array('msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'),
                       'BRW012'=>array('msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'),
                       'BRW013'=>array('msg'=>'Failed to Define TargetId. RawId used instead','type'=>'warning'),
                       'BRW014'=>array('msg'=>'No Kind Code or Generation Format Defined','type'=>'warning'),
                       'BRW015'=>array('msg'=>'No Date Found. Trigger lookup','type'=>'warning'),
                       'BRW016'=>array('msg'=>'Date Lookup Did not Find Anything','type'=>'warning'),
                       'BRW017'=>array('msg'=>'Year Replacement Failed. No Date Defined in the Input','type'=>'warning'),
                       'BRW018'=>array('msg'=>'Year Defined in Target Format, but no Date Defined','type'=>'warning'),
                       'BRW019'=>array('msg'=>'Document Found in DB','type'=>'warning'),
                       'BRW020'=>array('msg'=>'Kind code replaced by preferred lookup value','type'=>'warning'),
                       'BRW021'=>array('msg'=>'Kind code replaced but not with first preferred lookup value','type'=>'warning'),
                       'BRW022'=>array('msg'=>'Lookup found values which are not in preferred list','type'=>'warning'),
                       'BRW023'=>array('msg'=>'Kind code lookup did not find anything','type'=>'warning'),
                       'BRW024'=>array('msg'=>'Lookup for kind codes with date contains more than one value','type'=>'warning'),
                       'BRW026'=>array('msg'=>'Lookup found documents which are not in preferred list','type'=>'warning'),
                       'BRW027'=>array('msg'=>'Invalid date format','type'=>'warning'),
                       'BRW028'=>array('msg'=>'Invalid date format','type'=>'warning'),
                       'BRW030'=>array('msg'=>'Kind code lookup without date found values','type'=>'warning'),
                       'BRW031'=>array('msg'=>'No Kindcode format defined, kindcode first char matches a valid kindcode','type'=>'warning'),
                       'BRW032'=>array('msg'=>'No Kindcode format defined, kindcode matches a valid kindcode','type'=>'warning'),
                      );
    
    
}
?>
